// Code generated by go generate; DO NOT EDIT.
// +build linux_bpf

package runtime

var RuntimeSecurity = NewRuntimeAsset("runtime-security.c", "13b073a892c7700a87b660105a5f455db1cd688bbd7385788fd5adeecb12905e")
